### ISSUE TITLE
Create Database Models

### ISSUE THREAD

**Issue by BlazeDex** [BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final#11]
```[tasklist]
### Tasks
- [x] Create Databases
- [ ] Create model for User
- [ ] Create model for Routine
- [ ] Create models for Serie
- [ ] Create model for Post
- [ ] Create models for Message
- [ ] Create models for Comment
- [ ] Create model for Likes
- [ ] Create model for Followers
```

**Comment by BlazeDex** [comment]
![Image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73453092/62c5b8a1-f60d-49b9-a79c-f97028204d88)
