### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by AnaCarrizales** [BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final#14]
```[tasklist]
### Tasks
```

- [x] User must be able to sign up using google account
- [x] User must be able to sign up using facebook
- [x] User must be able to sign up as host
