### ISSUE TITLE
Create Rails Project Template

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final#4]
Create Rails project in order to start the entire application's development.
```[tasklist]
### Tasks
- [x] Create the project's structure.
- [x] Configure the project in order to use PostgreSQL.
- [x] Ensure that the project can be successfully runned.
- [x] Install the selected design framework.
```
