### ISSUE TITLE
Create Final Users Accounts System

### ISSUE THREAD

**Issue by AnaCarrizales** [BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final#5]
All the final users will be able to create, authenticate and access their accounts.
```[tasklist]
### Tasks
- [ ] https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/issues/8
- [x] Generate a sign in screen.
- [x] Generate a sign up screen.
- [x] Allow the users to authenticate their emails.
- [x] Add Facebook accounts linkins.
- [x] Add Google accounts linkins.
```
